/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    MyPerson: typeof import('./src/components/MyPerson.vue')['default']
    Person: typeof import('./src/components/Person.vue')['default']
  }
}
